import type { ArchetypeId, AttributeId, MagicSchool } from "@embertrail/shared";

export interface ArchetypeDef {
  id: ArchetypeId;
  nameKey: string;
  descKey: string;
  minAttrs: Partial<Record<AttributeId, number>>;
  skillBias: string[];
  combatSkill: string;
  isCaster: boolean;
  schoolFocus?: MagicSchool;
  lifeMod: number;
  focusMod: number;
  startingGear: string[];
  portraitBase: string;
}

export const ARCHETYPES: ArchetypeDef[] = [
  {
    id: "steelguard",
    nameKey: "arch.steelguard",
    descKey: "arch.steelguard.desc",
    minAttrs: { str: 12, cou: 11, con: 11 },
    skillBias: ["swords", "shields", "selfControl", "endurance", "tactics"],
    combatSkill: "swords",
    isCaster: false,
    lifeMod: 8,
    focusMod: 0,
    startingGear: ["longsword", "wooden_shield", "leather_armor", "boots", "rations_pack"],
    portraitBase: "steelguard",
  },
  {
    id: "seafarer",
    nameKey: "arch.seafarer",
    descKey: "arch.seafarer.desc",
    minAttrs: { str: 11, con: 12, cou: 11 },
    skillBias: ["axes", "swim", "carouse", "intimidate", "endurance"],
    combatSkill: "axes",
    isCaster: false,
    lifeMod: 7,
    focusMod: 0,
    startingGear: ["battle_axe", "leather_armor", "boots", "rations_pack"],
    portraitBase: "seafarer",
  },
  {
    id: "stonekin",
    nameKey: "arch.stonekin",
    descKey: "arch.stonekin.desc",
    minAttrs: { str: 11, con: 12, dex: 10 },
    skillBias: ["axes", "blunt", "repair", "locks", "climb"],
    combatSkill: "axes",
    isCaster: false,
    lifeMod: 7,
    focusMod: 0,
    startingGear: ["warhammer", "leather_armor", "boots", "lockpicks", "rations_pack"],
    portraitBase: "stonekin",
  },
  {
    id: "shadowhand",
    nameKey: "arch.shadowhand",
    descKey: "arch.shadowhand.desc",
    minAttrs: { dex: 12, agi: 11, int: 10 },
    skillBias: ["swords", "locks", "pickpocket", "sneak", "hide", "streetwise"],
    combatSkill: "swords",
    isCaster: false,
    lifeMod: 5,
    focusMod: 0,
    startingGear: ["shortsword", "leather_armor", "boots", "lockpicks", "rations_pack"],
    portraitBase: "shadowhand",
  },
  {
    id: "trickster",
    nameKey: "arch.trickster",
    descKey: "arch.trickster.desc",
    minAttrs: { cha: 12, dex: 11, agi: 10 },
    skillBias: ["throwing", "lie", "music", "dance", "pickpocket", "persuade"],
    combatSkill: "throwing",
    isCaster: false,
    lifeMod: 5,
    focusMod: 0,
    startingGear: ["throwing_knives", "cloth_armor", "boots", "lute", "rations_pack"],
    portraitBase: "trickster",
  },
  {
    id: "hexweaver",
    nameKey: "arch.hexweaver",
    descKey: "arch.hexweaver.desc",
    minAttrs: { cle: 12, int: 11, cha: 10 },
    skillBias: ["arcaneLore", "alchemy", "herbLore", "persuade", "selfControl"],
    combatSkill: "blunt",
    isCaster: true,
    schoolFocus: "mind",
    lifeMod: 4,
    focusMod: 12,
    startingGear: ["staff", "cloth_armor", "boots", "herb_pouch", "rations_pack"],
    portraitBase: "hexweaver",
  },
  {
    id: "wildcaller",
    nameKey: "arch.wildcaller",
    descKey: "arch.wildcaller.desc",
    minAttrs: { int: 11, con: 11, cle: 11 },
    skillBias: ["herbLore", "animalLore", "survival", "treatWounds", "alchemy"],
    combatSkill: "blunt",
    isCaster: true,
    schoolFocus: "nature",
    lifeMod: 5,
    focusMod: 10,
    startingGear: ["staff", "leather_armor", "boots", "herb_pouch", "rations_pack"],
    portraitBase: "wildcaller",
  },
  {
    id: "magister",
    nameKey: "arch.magister",
    descKey: "arch.magister.desc",
    minAttrs: { cle: 13, int: 11 },
    skillBias: ["arcaneLore", "history", "languages", "alchemy", "selfControl"],
    combatSkill: "blunt",
    isCaster: true,
    schoolFocus: "elemental",
    lifeMod: 3,
    focusMod: 16,
    startingGear: ["staff", "cloth_armor", "boots", "spellbook", "rations_pack"],
    portraitBase: "magister",
  },
  {
    id: "pathfinder",
    nameKey: "arch.pathfinder",
    descKey: "arch.pathfinder.desc",
    minAttrs: { dex: 11, int: 11, con: 10 },
    skillBias: ["bows", "track", "survival", "orient", "perception", "animalLore"],
    combatSkill: "bows",
    isCaster: false,
    lifeMod: 6,
    focusMod: 0,
    startingGear: ["shortbow", "arrows", "leather_armor", "boots", "rations_pack"],
    portraitBase: "pathfinder",
  },
  {
    id: "leafborn",
    nameKey: "arch.leafborn",
    descKey: "arch.leafborn.desc",
    minAttrs: { dex: 12, cha: 11, agi: 11 },
    skillBias: ["bows", "persuade", "etiquette", "history", "perception"],
    combatSkill: "bows",
    isCaster: true,
    schoolFocus: "healing",
    lifeMod: 5,
    focusMod: 8,
    startingGear: ["shortbow", "arrows", "leather_armor", "boots", "rations_pack"],
    portraitBase: "leafborn",
  },
  {
    id: "grovekin",
    nameKey: "arch.grovekin",
    descKey: "arch.grovekin.desc",
    minAttrs: { dex: 11, int: 12, agi: 11 },
    skillBias: ["bows", "sneak", "hide", "track", "herbLore", "survival"],
    combatSkill: "bows",
    isCaster: true,
    schoolFocus: "nature",
    lifeMod: 5,
    focusMod: 8,
    startingGear: ["shortbow", "arrows", "leather_armor", "boots", "herb_pouch", "rations_pack"],
    portraitBase: "grovekin",
  },
  {
    id: "frostborn",
    nameKey: "arch.frostborn",
    descKey: "arch.frostborn.desc",
    minAttrs: { cou: 11, int: 12, con: 11 },
    skillBias: ["bows", "survival", "weatherSense", "selfControl", "arcaneLore"],
    combatSkill: "bows",
    isCaster: true,
    schoolFocus: "elemental",
    lifeMod: 5,
    focusMod: 10,
    startingGear: ["shortbow", "arrows", "leather_armor", "boots", "rations_pack"],
    portraitBase: "frostborn",
  },
];

export const ARCHETYPE_BY_ID = Object.fromEntries(ARCHETYPES.map((a) => [a.id, a])) as Record<
  ArchetypeId,
  ArchetypeDef
>;
